# Generated by Django 4.2.6 on 2023-11-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_universities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='rating',
            new_name='reviews',
        ),
    ]
