# Generated by Django 4.2.6 on 2023-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_universities_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
