# Generated by Django 4.2.6 on 2023-12-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_university_id_alter_university_name_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=25),
        ),
        migrations.AddField(
            model_name='course',
            name='usefulness',
            field=models.CharField(default='Medium', max_length=25),
        ),
        migrations.AddField(
            model_name='course',
            name='workload',
            field=models.CharField(default='Medium', max_length=25),
        ),
    ]
