# Generated by Django 4.2.6 on 2023-12-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_course_id_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.CharField(default='Medium', max_length=25)),
                ('difficulty', models.CharField(default='Medium', max_length=25)),
                ('usefulness', models.CharField(default='Medium', max_length=25)),
                ('review', models.CharField(default='No review available', max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university')),
            ],
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
