# Generated by Django 4.2.6 on 2023-12-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_review_difficulty_alter_review_usefulness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.CharField(default='No professor available', max_length=50),
        ),
    ]
