# Generated by Django 4.2.6 on 2023-12-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_university_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='logo',
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
