# Generated by Django 4.2.6 on 2023-12-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_university_logo_university_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='usefulness',
        ),
        migrations.RemoveField(
            model_name='course',
            name='workload',
        ),
    ]
