# Generated by Django 4.2.6 on 2023-12-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_review_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='person',
            new_name='username',
        ),
    ]
