# Generated by Django 4.2.6 on 2023-12-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_review_person'),
        ('api', '0022_course_difficulty_course_usefulness_course_workload'),
    ]

    operations = [
    ]
