# Generated by Django 4.2.6 on 2023-12-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_person_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
    ]
