# Generated by Django 4.2.6 on 2023-12-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20231206_0621'),
        ('api', '0024_remove_review_username'),
    ]

    operations = [
    ]
