# Generated by Django 4.2.6 on 2023-12-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20231206_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='usefulness',
        ),
        migrations.RemoveField(
            model_name='course',
            name='workload',
        ),
    ]
