# Generated by Django 4.2.6 on 2023-12-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_alter_review_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
