# Generated by Django 4.2.6 on 2023-12-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_alter_review_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='person',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='No user available', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
