# Generated by Django 4.2.6 on 2023-12-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_review_dislikes_review_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
