# Generated by Django 4.2.6 on 2023-12-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_review_dislikes_remove_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='ikes',
            field=models.IntegerField(default=0),
        ),
    ]
