version: "3.2"

services:
  backend:
    restart: always
    container_name: backend
    command: bash -c "python rateMyCourse/manage.py runserver 0.0.0.0:8000"
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      


  # fontend:
  #   restart: always
  #   command : npm start
  #   container_name: fronte
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   stdin_open: true
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"